---Test suite for markdown-plus.nvim list management
---Tests list parsing, empty list detection, and list continuation
---@diagnostic disable: undefined-field
local list = require("markdown-plus.list")

describe("markdown-plus list management", function()
  local buf

  before_each(function()
    buf = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_option(buf, "filetype", "markdown")
    vim.api.nvim_set_current_buf(buf)
  end)

  after_each(function()
    if vim.api.nvim_buf_is_valid(buf) then
      vim.api.nvim_buf_delete(buf, { force = true })
    end
  end)

  describe("parse_list_line", function()
    it("parses unordered list items", function()
      local info = list.parse_list_line("- List item")
      assert.is_not_nil(info)
      assert.are.equal("unordered", info.type)
      assert.are.equal("-", info.marker)
    end)

    it("parses ordered list items", function()
      local info = list.parse_list_line("1. List item")
      assert.is_not_nil(info)
      assert.are.equal("ordered", info.type)
    end)

    it("parses parenthesized ordered list items", function()
      local info = list.parse_list_line("1) List item")
      assert.is_not_nil(info)
      assert.are.equal("ordered_paren", info.type)
      assert.are.equal("1)", info.marker)
    end)

    it("parses parenthesized lowercase letter list items", function()
      local info = list.parse_list_line("a) List item")
      assert.is_not_nil(info)
      assert.are.equal("letter_lower_paren", info.type)
      assert.are.equal("a)", info.marker)
    end)

    it("parses parenthesized uppercase letter list items", function()
      local info = list.parse_list_line("A) List item")
      assert.is_not_nil(info)
      assert.are.equal("letter_upper_paren", info.type)
      assert.are.equal("A)", info.marker)
    end)

    it("parses task list items", function()
      local info = list.parse_list_line("- [ ] Unchecked task")
      assert.is_not_nil(info)
      assert.is_not_nil(info.checkbox)
    end)

    it("parses parenthesized ordered task list items", function()
      local info = list.parse_list_line("1) [ ] Unchecked task")
      assert.is_not_nil(info)
      assert.are.equal("ordered_paren", info.type)
      assert.is_not_nil(info.checkbox)
    end)

    it("parses multi-letter lowercase list items", function()
      local info = list.parse_list_line("aa. List item")
      assert.is_not_nil(info)
      assert.are.equal("letter_lower", info.type)
      assert.are.equal("aa.", info.marker)
    end)

    it("parses multi-letter uppercase list items", function()
      local info = list.parse_list_line("AB. List item")
      assert.is_not_nil(info)
      assert.are.equal("letter_upper", info.type)
      assert.are.equal("AB.", info.marker)
    end)

    it("parses multi-letter parenthesized lowercase list items", function()
      local info = list.parse_list_line("aa) List item")
      assert.is_not_nil(info)
      assert.are.equal("letter_lower_paren", info.type)
      assert.are.equal("aa)", info.marker)
    end)

    it("parses multi-letter parenthesized uppercase list items", function()
      local info = list.parse_list_line("AB) List item")
      assert.is_not_nil(info)
      assert.are.equal("letter_upper_paren", info.type)
      assert.are.equal("AB)", info.marker)
    end)

    it("returns nil for non-list lines", function()
      local info = list.parse_list_line("Not a list")
      assert.is_nil(info)
    end)
  end)

  describe("is_empty_list_item", function()
    it("detects empty list items", function()
      local info = list.parse_list_line("- ")
      local is_empty = list.is_empty_list_item("- ", info)
      assert.is_true(is_empty)
    end)

    it("detects non-empty list items", function()
      local info = list.parse_list_line("- Content")
      local is_empty = list.is_empty_list_item("- Content", info)
      assert.is_false(is_empty)
    end)
  end)

  describe("index_to_letter", function()
    it("converts single digit indices to lowercase letters", function()
      assert.are.equal("a", list.index_to_letter(1, false))
      assert.are.equal("b", list.index_to_letter(2, false))
      assert.are.equal("z", list.index_to_letter(26, false))
    end)

    it("converts single digit indices to uppercase letters", function()
      assert.are.equal("A", list.index_to_letter(1, true))
      assert.are.equal("B", list.index_to_letter(2, true))
      assert.are.equal("Z", list.index_to_letter(26, true))
    end)

    it("converts multi-digit indices to lowercase letter sequences", function()
      assert.are.equal("aa", list.index_to_letter(27, false))
      assert.are.equal("ab", list.index_to_letter(28, false))
      assert.are.equal("az", list.index_to_letter(52, false))
      assert.are.equal("ba", list.index_to_letter(53, false))
      assert.are.equal("zz", list.index_to_letter(702, false))
      assert.are.equal("aaa", list.index_to_letter(703, false))
    end)

    it("converts multi-digit indices to uppercase letter sequences", function()
      assert.are.equal("AA", list.index_to_letter(27, true))
      assert.are.equal("AB", list.index_to_letter(28, true))
      assert.are.equal("AZ", list.index_to_letter(52, true))
      assert.are.equal("BA", list.index_to_letter(53, true))
      assert.are.equal("ZZ", list.index_to_letter(702, true))
      assert.are.equal("AAA", list.index_to_letter(703, true))
    end)
  end)
end)
